### ISSUE TITLE
Enhancement: Multiline information for GM instead of character name

### ISSUE THREAD

**Issue by CePeU** [farling42/fvtt-gmtext-in-notes#1]
In analogy for notes it would be great if token names could be changed for a GM to show additional information (multiline text). The idea would be that while hovering over an icon the GM could see GM informations stored for that icon.

For example:
"The goblin leader will flee if magic is used"

Maybe there is a simpler way to accomplish this but the logic would be similar to notices.

**Comment by farling42** [comment]
Since this request isn't about scene Notes it is a bit outside the scope of my module.

I see that "theRipper93" has a premium module called "Token Notes" which might be suitable for your use case. https://theripper93.com/#/module/token-notes
